FAIL ./yatze.test.ts
  Chance
    ✓ roll 5 dice (2 ms)
  Yatze
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Ones
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Twos
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Threes, Fours, Fives, Sixes
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully (1 ms)
  Pairs
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Two Pairs
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully (1 ms)
  Three of a Kind
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully (1 ms)
  Four of a Kind
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Small Straight
    ✓ roll 5 dice successfully (1 ms)
    ✕ roll 5 dice unsuccessfully (2 ms)

  ● Small Straight › roll 5 dice unsuccessfully

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 16

      101 |   })
      102 |   it('roll 5 dice unsuccessfully', () => {
    > 103 |     expect(roll([2,2,2,5,5],"Small Straight")).toEqual(0);
          |                                                ^
      104 |     expect(roll([2,2,2,2,2],"Small Straight")).toEqual(0);
      105 |   })
      106 | });

      at Object.<anonymous> (yatze.test.ts:103:48)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 18 passed, 19 total
Snapshots:   0 total
Time:        2.731 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest --maxWorkers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2025-05-05T08_01_18_553Z-debug.log
